### ISSUE TITLE
Optional Paramaters are not optional

### ISSUE THREAD

**Issue by stefangries** [lolouk44/xiaomi_mi_scale_ha_add_on#3]
Optional parameters like USER3_XXX in config.json are not marked as optional.

As described here, you should just add an questionmark to the datatype in the schema object in config.json.
https://developers.home-assistant.io/docs/add-ons/configuration#options--schema

**Comment by lolouk44** [comment]
Thanks for the feedback. Just pushed a change
Will give it a couple of days before I update the release number in case I get something else, I've only just installed hass.io 2 days ago just so I could create an Add-On. I'm sure there are other issues ;)
